# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla

---

# Simple Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: simple-cluster
  namespace: scylla
spec:
  version: 4.6.3
  agentVersion: 3.0.0
  developerMode: true
  cpuset: true
  network:
    hostNetworking: true
  sysctls:
  - "fs.aio-max-nr=2097152"  
  datacenter:
    name: ap-south-1
    racks:
      - name: ap-south-1a
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 3
        storage:
          storageClassName: ebs-main-sc
          capacity: 5Gi
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
        placement:
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters
              effect: NoSchedule    
        volumes:
          - name: coredumpfs
            hostPath:
              path: /tmp/coredumps
        volumeMounts:
          - mountPath: /tmp/coredumps
            name: coredumpfs
