# Namespace where the Scylla Cluster will be created
apiVersion: v1
kind: Namespace
metadata:
  name: scylla

---

# Scylla Cluster
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-cluster
  namespace: scylla
spec:
  version: 5.0.5
  agentVersion: 3.0.1
  cpuset: true
  automaticOrphanedNodeCleanup: true
  sysctls:
    - "fs.aio-max-nr=2097152"
  network:
    hostNetworking: true
  datacenter:
    name: <gcp_region>
    racks:
      - name: <gcp_zone>
        scyllaConfig: "scylla-config"
        scyllaAgentConfig: "scylla-agent-config"
        members: 2
        storage:
          storageClassName: local-raid-disks
          capacity: 2995G
        resources:
          limits:
            cpu: 30
            memory: 115G
          requests:
            cpu: 30
            memory: 115G
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - <gcp_zone>
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters
              effect: NoSchedule
